### ISSUE TITLE
Get black screen on an emulate android device

### ISSUE THREAD

**Issue by sandrhymend** [ionicthemes/ion2fullapp#19] opened 2018-09-10 16:30 UTC
run ionic cordova emulate android

Sandras-MBP:ion2fullapp-elite sandramendoza$ ionic cordova emulate android
> ionic-app-scripts build --target cordova --platform android
[08:30:49]  ionic-app-scripts 3.1.8 
[08:30:50]  build dev started ... 
[08:30:50]  clean started ... 
[08:30:50]  clean finished in 3 ms 
[08:30:50]  copy started ... 
[08:30:50]  deeplinks started ... 
[08:30:50]  deeplinks finished in 167 ms 
[08:30:50]  transpile started ... 
[08:30:55]  transpile finished in 4.96 s 
[08:30:55]  preprocess started ... 
[08:30:55]  preprocess finished in less than 1 ms 
[08:30:55]  webpack started ... 
[08:30:57]  copy finished in 7.08 s 
[08:31:03]  webpack finished in 8.13 s 
[08:31:03]  sass started ... 
Without `from` option PostCSS could generate wrong source map and will not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning.
[08:31:06]  sass finished in 2.67 s 
[08:31:06]  postprocess started ... 
[08:31:06]  postprocess finished in 10 ms 
[08:31:06]  lint started ... 
[08:31:06]  build dev finished in 16.13 s 
[08:31:10]  tslint: src/pages/google-login/google-login.service.ts, line: 5 
            All imports are unused. 

       L4:  import { GooglePlus } from '@ionic-native/google-plus';
       L5:  import firebase from 'firebase';
       L6:  import { AngularFireAuth } from 'angularfire2/auth';

[08:31:10]  tslint: src/pages/google-login/google-login.service.ts, line: 6 
            All imports are unused. 

       L5:  import firebase from 'firebase';
       L6:  import { AngularFireAuth } from 'angularfire2/auth';
       L7:  import { Observable } from 'rxjs/Observable';

            All imports are unused. 

       L6:  import { AngularFireAuth } from 'angularfire2/auth';
[08:31:10]  tslint: src/pages/google-login/google-login.service.ts, line: 7 
[08:31:10]  tslint: src/pages/google-login/google-login.service.ts, line: 12 
       L7:  import { Observable } from 'rxjs/Observable';

            All imports are unused. 

      L11:  import { environment } from '../../environment/environment';
      L12:  import { Platform } from 'ionic-angular';

[08:31:10]  lint finished in 4.22 s 
> cordova emulate android
Discovered plugin "call-number" in config.xml. Adding it to the project
Failed to restore plugin "call-number" from config.xml. You might need to try adding it again. Error: Failed to fetch plugin call-number@0.0.2 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 243 Error output:
npm WARN checkPermissions Missing write access to /Users/sandramendoza/Documents/Ionic-Projects/ion2fullapp-elite/node_modules/call-number
npm ERR! path /Users/sandramendoza/Documents/Ionic-Projects/ion2fullapp-elite/node_modules/call-number
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/Users/sandramendoza/Documents/Ionic-Projects/ion2fullapp-elite/node_modules/call-number'
npm ERR!  { Error: EACCES: permission denied, access '/Users/sandramendoza/Documents/Ionic-Projects/ion2fullapp-elite/node_modules/call-number'
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/Users/sandramendoza/Documents/Ionic-Projects/ion2fullapp-elite/node_modules/call-number\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/Users/sandramendoza/Documents/Ionic-Projects/ion2fullapp-elite/node_modules/call-number' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sandramendoza/.npm/_logs/2018-09-10T15_31_19_185Z-debug.log
ANDROID_HOME=/Users/sandramendoza/Library/Android/sdk
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home
Subproject Path: CordovaLib
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
	at build_6wsbfl7mj1f85u9c6st11bqt3.run(/Users/sandramendoza/Documents/Ionic-Projects/ion2fullapp-elite/platforms/android/build.gradle:143)
useNewCruncher has been deprecated. It will be removed in a future version of the gradle plugin. New cruncher is now always enabled.
The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.
Incremental java compilation is an incubating feature.
The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.
:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:preReleaseBuild UP-TO-DATE
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl UP-TO-DATE
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:compileLint UP-TO-DATE
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugShaders UP-TO-DATE
:CordovaLib:compileDebugShaders UP-TO-DATE
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:compileDebugRenderscript UP-TO-DATE
:CordovaLib:generateDebugResValues UP-TO-DATE
:CordovaLib:generateDebugResources UP-TO-DATE
:CordovaLib:packageDebugResources UP-TO-DATE
:CordovaLib:processDebugManifest UP-TO-DATE
:CordovaLib:generateDebugBuildConfig UP-TO-DATE
:CordovaLib:processDebugResources UP-TO-DATE
:CordovaLib:generateDebugSources UP-TO-DATE
:CordovaLib:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:CordovaLib:compileDebugJavaWithJavac UP-TO-DATE
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug UP-TO-DATE
:CordovaLib:mergeDebugJniLibFolders UP-TO-DATE
:CordovaLib:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
:CordovaLib:transformNative_libsWithSyncJniLibsForDebug UP-TO-DATE
:CordovaLib:bundleDebug UP-TO-DATE
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl UP-TO-DATE
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseShaders UP-TO-DATE
:CordovaLib:compileReleaseShaders UP-TO-DATE
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles UP-TO-DATE
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:compileReleaseRenderscript UP-TO-DATE
:CordovaLib:generateReleaseResValues UP-TO-DATE
:CordovaLib:generateReleaseResources UP-TO-DATE
:CordovaLib:packageReleaseResources UP-TO-DATE
:CordovaLib:processReleaseManifest UP-TO-DATE
:CordovaLib:generateReleaseBuildConfig UP-TO-DATE
:CordovaLib:processReleaseResources UP-TO-DATE
:CordovaLib:generateReleaseSources UP-TO-DATE
:CordovaLib:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:CordovaLib:compileReleaseJavaWithJavac UP-TO-DATE
:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:CordovaLib:mergeReleaseJniLibFolders UP-TO-DATE
:CordovaLib:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:CordovaLib:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
:CordovaLib:bundleRelease UP-TO-DATE
:prepareAndroidArchLifecycleRuntime103Library UP-TO-DATE
:prepareComAndroidSupportAnimatedVectorDrawable2702Library UP-TO-DATE
:prepareComAndroidSupportAppcompatV72702Library UP-TO-DATE
:prepareComAndroidSupportCardviewV72702Library UP-TO-DATE
:prepareComAndroidSupportCustomtabs2702Library UP-TO-DATE
:prepareComAndroidSupportSupportCompat2702Library UP-TO-DATE
:prepareComAndroidSupportSupportCoreUi2702Library UP-TO-DATE
:prepareComAndroidSupportSupportCoreUtils2702Library UP-TO-DATE
:prepareComAndroidSupportSupportFragment2702Library UP-TO-DATE
:prepareComAndroidSupportSupportMediaCompat2702Library UP-TO-DATE
:prepareComAndroidSupportSupportV42702Library UP-TO-DATE
:prepareComAndroidSupportSupportVectorDrawable2702Library UP-TO-DATE
:prepareComFacebookAndroidFacebookAndroidSdk4360Library UP-TO-DATE
:prepareComFacebookAndroidFacebookApplinks4360Library UP-TO-DATE
:prepareComFacebookAndroidFacebookCommon4360Library UP-TO-DATE
:prepareComFacebookAndroidFacebookCore4360Library UP-TO-DATE
:prepareComFacebookAndroidFacebookLogin4360Library UP-TO-DATE
:prepareComFacebookAndroidFacebookMarketing4360Library UP-TO-DATE
:prepareComFacebookAndroidFacebookMessenger4360Library UP-TO-DATE
:prepareComFacebookAndroidFacebookPlaces4360Library UP-TO-DATE
:prepareComFacebookAndroidFacebookShare4360Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesAuth1180Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesAuthApiPhone1180Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesAuthApiPhoneLicense1180Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesAuthBase1180Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesAuthBaseLicense1180Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesBase1180Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesBaseLicense1180Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesBasement1180Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesBasementLicense1180Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesIdentity1180Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesIdentityLicense1180Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesTasks1180Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesTasksLicense1180Library UP-TO-DATE
:prepareComSoundcloudAndroidAndroidCrop100Library UP-TO-DATE
:prepareOrgApacheCordovaCordovaLib630DebugLibrary UP-TO-DATE
:prepareDebugDependencies
:compileDebugAidl UP-TO-DATE
:compileDebugRenderscript UP-TO-DATE
:generateDebugBuildConfig UP-TO-DATE
:generateDebugResValues UP-TO-DATE
:generateDebugResources UP-TO-DATE
:mergeDebugResources UP-TO-DATE
:processDebugManifest UP-TO-DATE
:processDebugResources UP-TO-DATE
:generateDebugSources UP-TO-DATE
:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:compileDebugJavaWithJavac UP-TO-DATE
:compileDebugNdk UP-TO-DATE
:compileDebugSources UP-TO-DATE
:mergeDebugShaders UP-TO-DATE
:compileDebugShaders UP-TO-DATE
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets UP-TO-DATE
:transformClassesWithDexForDebug UP-TO-DATE
:mergeDebugJniLibFolders UP-TO-DATE
:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
:processDebugJavaRes UP-TO-DATE
:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
:validateSigningDebug
:packageDebug UP-TO-DATE
:assembleDebug UP-TO-DATE
:cdvBuildDebug UP-TO-DATE

BUILD SUCCESSFUL

Total time: 1.594 secs
Built the following apk(s): 
	/Users/sandramendoza/Documents/Ionic-Projects/ion2fullapp-elite/platforms/android/build/outputs/apk/android-debug.apk
ANDROID_HOME=/Users/sandramendoza/Library/Android/sdk
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home
No emulator specified, defaulting to Galaxy_Nexus_API_22
Waiting for emulator to start...
emulator: Requested console port 5584: Inferring adb port 5585.
emulator: WARNING: encryption is off
Waiting for emulator to boot (this may take a while)...BOOT COMPLETE
Skipping build...
Built the following apk(s): 
	/Users/sandramendoza/Documents/Ionic-Projects/ion2fullapp-elite/platforms/android/build/outputs/apk/android-debug.apk
Using apk: /Users/sandramendoza/Documents/Ionic-Projects/ion2fullapp-elite/platforms/android/build/outputs/apk/android-debug.apk
Package name: com.startapplabs.ion2FullApp.elite
INSTALL SUCCESS
LAUNCH SUCCESS
<img width="432" alt="screen shot 2018-09-10 at 9 18 06 am" src="https://user-images.githubusercontent.com/38015544/45310742-02591f00-b4dc-11e8-9044-4b2d1e68e378.png">

Any help? :(

**Comment by namtsby** [comment] 2018-09-14 13:00
I have tried both the grable version 4.10.1 and the grable 4.1.0 on Android version 6.3.0.
But I still see a black screen.
ios works well.
Please tell me how to solve it.

**Comment by djabif** [comment] 2018-09-14 13:04
Hi, can you please try to delete call-number plugin and then try to build and emulate the project again? 
I will try to reproduce it on my end and will let you know if I find something.

**Comment by namtsby** [comment] 2018-09-14 13:11
<plugin name="mx.ferreyra.callnumber" spec="0.0.2" />
    <plugin name="call-number" />

Can I erase both?

**Comment by namtsby** [comment] 2018-09-14 13:29
Even though it is erased by many methods, the phone plug-in is finally recreated in Android version 6.3.0 at the end. Can't erase.

**Comment by djabif** [comment] 2018-09-14 13:35
To delete it properly you need to use` ionic cordova plugin rm call-number` and also uninstall the associated Ionic Native package using `npm uninstall --save @ionic-native/<npm-name-of-plugin>`

**Comment by namtsby** [comment] 2018-09-14 13:43
Yeah. That's how I erased it. But it's still been reinstalled. Could you look at the code below?


namui-MacBook-Pro:ion2fullapp-elite namionic cordova plugin rm call-number
> cordova plugin remove call-number --save
Uninstalling call-number from android

Uninstalling call-number from ios

Removing "call-number"

Removing plugin call-number from config.xml file...
Removing call-number from package.json


namui-MacBook-Pro:ion2fullapp-elite nam$ npm uninstall --save @ionic-native/call-number
up to date in 4.592s
namui-MacBook-Pro:ion2fullapp-elite nam$ ionic cordova run android --device -l
Starting app-scripts server: --address 0.0.0.0 --port 8100 --livereload-port 
35729 --dev-logger-port 53703 --nobrowser --iscordovaserve --platform android 
--target cordova - Ctrl+C to cancel
[22:40:44]  watch started ... 
[22:40:44]  build dev started ... 
[22:40:44]  clean started ... 
[22:40:44]  clean finished in 3 ms 
[22:40:44]  copy started ... 
[22:40:45]  deeplinks started ... 
[22:40:45]  deeplinks finished in 228 ms 
[22:40:45]  transpile started ... 
[22:40:52]  transpile finished in 7.23 s 
[22:40:52]  preprocess started ... 
[22:40:52]  preprocess finished in less than 1 ms 
[22:40:52]  webpack started ... 
[22:40:56]  copy finished in 11.48 s 
[22:41:03]  webpack finished in 11.23 s 
[22:41:03]  sass started ... 
Without `from` option PostCSS could generate wrong source map and will not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning.
[22:41:07]  sass finished in 3.39 s 
[22:41:07]  postprocess started ... 
[22:41:07]  postprocess finished in 8 ms 
[22:41:07]  lint started ... 
[22:41:07]  build dev finished in 22.35 s 
[22:41:07]  watch ready in 22.54 s 
[22:41:07]  dev server running: http://localhost:8100/ 

[OK] Development server running!
     Local: http://localhost:8100
     External: http://192.168.40.52:8100
     

> cordova run android --device
Discovered plugin "mx.ferreyra.callnumber" in config.xml. Adding it to the project

[22:41:14]  lint finished in 7.14 s 
Installing "call-number" for android

ANDROID_HOME=/Users/nam/Library/Android/sdk/
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home
Subproject Path: CordovaLib
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.

	at build_94t9k02nprcgjqcg4128tgy0o.run(/Users/nam/Desktop/ion2fullapp-elite/platforms/android/build.gradle:143)

The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.

Incremental java compilation is an incubating feature.

The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.

:clean

:CordovaLib:clean


BUILD SUCCESSFUL


Total time: 4.587 secs
Installing "call-number" for ios

ANDROID_HOME=/Users/nam/Library/Android/sdk/
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home
Subproject Path: CordovaLib
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.

	at build_94t9k02nprcgjqcg4128tgy0o.run(/Users/nam/Desktop/ion2fullapp-elite/platforms/android/build.gradle:143)

The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.

Incremental java compilation is an incubating feature.

The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.

:preBuild
 
UP-TO-DATE
:preDebugBuild
 
UP-TO-DATE

:checkDebugManifest

:preReleaseBuild
 
UP-TO-DATE
:CordovaLib:preBuild
 
UP-TO-DATE
:CordovaLib:preDebugBuild
 
UP-TO-DATE

:CordovaLib:checkDebugManifest

:CordovaLib:prepareDebugDependencies

:CordovaLib:compileDebugAidl

:CordovaLib:compileDebugNdk
 
UP-TO-DATE
:CordovaLib:compileLint

:CordovaLib:copyDebugLint
 
UP-TO-DATE

:CordovaLib:mergeDebugShaders

:CordovaLib:compileDebugShaders

:CordovaLib:generateDebugAssets

:CordovaLib:mergeDebugAssets

:CordovaLib:mergeDebugProguardFiles
 
UP-TO-DATE
:CordovaLib:packageDebugRenderscript
 UP-TO-DATE
:CordovaLib:compileDebugRenderscript

:CordovaLib:generateDebugResValues

:CordovaLib:generateDebugResources

:CordovaLib:packageDebugResources

:CordovaLib:processDebugManifest

:CordovaLib:generateDebugBuildConfig

:CordovaLib:processDebugResources

:CordovaLib:generateDebugSources

:CordovaLib:incrementalDebugJavaCompilationSafeguard

:CordovaLib:compileDebugJavaWithJavac

:CordovaLib:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.

Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processDebugJavaRes
 
UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForDebug

:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug

:CordovaLib:mergeDebugJniLibFolders

:CordovaLib:transformNative_libsWithMergeJniLibsForDebug

:CordovaLib:transformNative_libsWithSyncJniLibsForDebug

:CordovaLib:bundleDebug
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseShaders
:CordovaLib:compileReleaseShaders
:CordovaLib:generateReleaseAssets
:CordovaLib:mergeReleaseAssets
:CordovaLib:mergeReleaseProguardFiles UP-TO-DATE
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:processReleaseManifest
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:incrementalReleaseJavaCompilationSafeguard
:CordovaLib:compileReleaseJavaWithJavac
:CordovaLib:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.

Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processReleaseJavaRes
 
UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForRelease

:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease

:CordovaLib:mergeReleaseJniLibFolders

:CordovaLib:transformNative_libsWithMergeJniLibsForRelease

:CordovaLib:transformNative_libsWithSyncJniLibsForRelease

:CordovaLib:bundleRelease

:prepareAndroidArchLifecycleRuntime103Library

:prepareComAndroidSupportAnimatedVectorDrawable2702Library

:prepareComAndroidSupportAppcompatV72702Library

:prepareComAndroidSupportCardviewV72702Library

:prepareComAndroidSupportCustomtabs2702Library

:prepareComAndroidSupportSupportCompat2702Library

:prepareComAndroidSupportSupportCoreUi2702Library

:prepareComAndroidSupportSupportCoreUtils2702Library

:prepareComAndroidSupportSupportFragment2702Library

:prepareComAndroidSupportSupportMediaCompat2702Library

:prepareComAndroidSupportSupportV42702Library

:prepareComAndroidSupportSupportVectorDrawable2702Library

:prepareComFacebookAndroidFacebookAndroidSdk4360Library

:prepareComFacebookAndroidFacebookApplinks4360Library

:prepareComFacebookAndroidFacebookCommon4360Library

:prepareComFacebookAndroidFacebookCore4360Library
:prepareComFacebookAndroidFacebookLogin4360Library

:prepareComFacebookAndroidFacebookMarketing4360Library

:prepareComFacebookAndroidFacebookMessenger4360Library

:prepareComFacebookAndroidFacebookPlaces4360Library

:prepareComFacebookAndroidFacebookShare4360Library

:prepareComGoogleAndroidGmsPlayServicesAuth1180Library

:prepareComGoogleAndroidGmsPlayServicesAuthApiPhone1180Library

:prepareComGoogleAndroidGmsPlayServicesAuthApiPhoneLicense1180Library

:prepareComGoogleAndroidGmsPlayServicesAuthBase1180Library

:prepareComGoogleAndroidGmsPlayServicesAuthBaseLicense1180Library

:prepareComGoogleAndroidGmsPlayServicesBase1180Library

:prepareComGoogleAndroidGmsPlayServicesBaseLicense1180Library

:prepareComGoogleAndroidGmsPlayServicesBasement1180Library

:prepareComGoogleAndroidGmsPlayServicesBasementLicense1180Library

:prepareComGoogleAndroidGmsPlayServicesIdentity1180Library

:prepareComGoogleAndroidGmsPlayServicesIdentityLicense1180Library

:prepareComGoogleAndroidGmsPlayServicesTasks1180Library

:prepareComGoogleAndroidGmsPlayServicesTasksLicense1180Library

:prepareComSoundcloudAndroidAndroidCrop100Library

:prepareOrgApacheCordovaCordovaLib630DebugLibrary

:prepareDebugDependencies

:compileDebugAidl

:compileDebugRenderscript

:generateDebugBuildConfig

:generateDebugResValues

:generateDebugResources

:mergeDebugResources

:processDebugManifest

:processDebugResources

:generateDebugSources
:incrementalDebugJavaCompilationSafeguard

:compileDebugJavaWithJavac

:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:compileDebugNdk
 UP-TO-DATE
:compileDebugSources

:mergeDebugShaders

:compileDebugShaders

:generateDebugAssets

:mergeDebugAssets

:transformClassesWithDexForDebug

:mergeDebugJniLibFolders

:transformNative_libsWithMergeJniLibsForDebug

:processDebugJavaRes
 
UP-TO-DATE
:transformResourcesWithMergeJavaResForDebug

:validateSigningDebug

:packageDebug

:assembleDebug
:cdvBuildDebug


BUILD SUCCESSFUL

Total time: 27.093 secs
Built the following apk(s): 
	/Users/nam/desktop/ion2fullapp-elite/platforms/android/build/outputs/apk/android-debug.apk

ANDROID_HOME=/Users/nam/Library/Android/sdk/
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home
Skipping build...

Built the following apk(s): 
	/Users/nam/desktop/ion2fullapp-elite/platforms/android/build/outputs/apk/android-debug.apk

Using apk: /Users/nam/desktop/ion2fullapp-elite/platforms/android/build/outputs/apk/android-debug.apk

Package name: com.startapplabs.ion2FullApp.elite

**Comment by djabif** [comment] 2018-09-14 16:39
Will try to reproduce the "black screen" and let you know.

**Comment by namtsby** [comment] 2018-09-18 18:30
It still doesn't work.
Do you happen to have a solution?
I purchased the elite version of code.
I was in a hurry...
If I may
Can you give me a Pro version of code?
Let's try the Pro version on Android.

**Comment by djabif** [comment] 2018-09-18 18:38
@rlantm, sorry for not getting back earlier. We found the problem is the Facebook Connect plugin. If you uninstall it, the black screen goes away. 

![](https://lh3.googleusercontent.com/-Y6xJ6eqT0kE/W6AUwLp4jdI/AAAAAAAAjhI/T5CCFY5t2YIlYT9sgdiNA9O1VdjFKnYtwCL0BGAYYCw/h600/2018-09-17.png)

We are currently working in a new version with a fix for that. Will let you know as soon as we finish the testing. Meanwhile, if you are going to use the emulator, you can build the app without facebook plugin.

**Comment by namtsby** [comment] 2018-09-18 18:47
Thank you.
I'll try.^^
I will wait for the new version.

**Comment by namtsby** [comment] 2018-09-19 06:48
If I delete the Facebook plug-in and associated code, I still see a black screen.
I tried ionic 3.20
Is this the correct version?
What version should I use?

**Comment by gonzad77** [comment] 2018-09-21 00:47
Check if your Google Play Package Name in facebook developer app is the same as wiget id in config.xml.

Then try follow this steps:

- cordova plugin rm cordova-plugin-facebook4

- cordova plugin add cordova-plugin-facebook4 --save --variable APP_ID="YOUR_APP_ID" --variable APP_NAME="YOUR_APP_NAME" --variable ANDROID_SDK_VERSION="4.28.0"

- ionic cordova emulate android

**Comment by namtsby** [comment] 2018-09-21 09:11
Thank you for your reply. I've finished setting up my Facebook!
But it doesn't work.
It works by erasing the Facebook plug-in. 
First of all, I have to use it like this.
I'll be waiting for the new version. Thank you.

**Comment by sandrhymend** [comment] 2018-09-21 22:49
It works for me now :)
$  ionic info
✔ Gathering environment info - done!

Ionic:

   ionic (Ionic CLI)  : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.8

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 6.3.0
   Cordova Plugins       : cordova-plugin-ionic 2.0.4, cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 1.2.1, (and 17 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/sandramendoza/Library/Android/sdk)
   NodeJS            : v8.11.4 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS Sierra

I just removed android folder and recreated it again.

**Comment by djabif** [comment] 2018-09-26 17:29
@rlantm new version 1.1.4 is out! Sorry for the delay.
You can download the new version from your account at ionicthemes.com by downloading the files again.
Closing this issue.

**Closed as completed by djabif** 2018-09-26 17:29 UTC
Labels: bug
